[programs.localnet]
monaco_protocol = "monacoUXKtUi6vKsQwaLyxmXKSievfNWEcYXTgkbCih"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn runJestTests"

[[test.genesis]]
address = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
program = "tests/anchor/protocol_product/protocol_product.so"
